<?php

namespace Eshop\ContactBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('cnt')
                   ->select('COUNT(cnt)');     // On sélectionne simplement COUNT(m)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    } 
}