<?php

namespace Eshop\ShopBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends EntityRepository
{

    /**
     * query for admin paginator
     *
     * @return QueryBuilder
     */
    public function getAllEmailTemplatesAdminQB()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('et')
            ->from('ShopBundle:EmailTemplate', 'et');

        return $qb;
    }
}
