<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * GProductcatfrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GProductcatfrRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('gpcfr')
                   ->select('COUNT(gpcfr)');     // On sélectionne simplement COUNT(cu)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    } 

    public function getGProductcatfrDistinct() 
    {
        $qb = $this->createQueryBuilder('gp')
                ->select('DISTINCT gp.cat1')
                ->from('ShopBundle:GProductcat', 'gp')
                ->where('gp.enable = :enable')
                ->setParameter('enable', 1)
                ->orderBy('gp.cat1', 'ASC')
                ->getQuery();

        return $qb;
    } 
    
    public function getGProductcatDistinct(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('DISTINCT(a.cat1)')
            ->from('ShopBundle:GProductcatfr', 'p')
            ->where('p.enable = 1')
            ->addOrderBy('a.cat1', 'ASC')
            ->getQuery()
            ->getResult();
    }


}
