<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfositeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfositeRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('is')
                   ->select('COUNT(is)');     // On sélectionne simplement COUNT(m)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    } 
}