<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfositelinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfositelinksRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('isl')
                   ->select('COUNT(isl)');     // On sélectionne simplement COUNT(e)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    } 
}