<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemesRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('thm')
                   ->select('COUNT(thm)');     // On sélectionne simplement COUNT(n)

        return (int) $qb->getQuery()
                         ->getSingleScalarResult(); // Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
    } 
}